all_items = [
    'Awesome Snack',
    'Berry Snow Bunny',
    'Big Egg',
    'Black Apple',
    'Block Block',
    'Block Meal',
    'Blue Apple',
    'Bone-In Cut',
    'Cake Mix',
    'Catch Card',
    'Catch Card SP',
    'Choco Pasta Dish',
    'Chocolate Cake',
    'Couple\'s Cake',
    'Courage Shell',
    'Dangerous Delight',
    'Dayzee Syrup',
    'Dayzee Tear',
    'Dried Shroom',
    'Dyllis Breakfast',
    'Dyllis Deluxe',
    'Dyllis Dinner',
    'Dyllis Dynamite',
    'Dyllis Lunch',
    'Dyllis Special',
    'Egg Bomb',
    'Electro Pop',
    'Emergency Ration',
    'Fire Burst',
    'Fresh Pasta Bunch',
    'Fresh Veggie',
    'Fried Egg',
    'Fried Shroom Plate',
    'Fruit Parfait',
    'Fruity Cake',
    'Fruity Hamburger',
    'Fruity Punch',
    'Fruity Shroom',
    'Ghost Shroom',
    'Gingerbread House',
    'Gold Bar',
    'Gold Bar x3',
    'Gold Medal',
    'Golden Choco-bar',
    'Golden Leaf',
    'Golden Meal',
    'Gorgeous Steak',
    'Gradual Syrup',
    'Hamburger',
    'Healthy Salad',
    'Heartful Cake',
    'Heavy Meal',
    'Herb Tea',
    'Honey Candy',
    'Honey Jar',
    'Honey Shroom',
    'Honey Super',
    'Horsetail',
    'Horsetail Tart',
    'Hot Dog',
    'Hot Sauce',
    'HP Plus',
    'Ice Storm',
    'Ink Pasta Dish',
    'Inky Sauce',
    'Inky Soup',
    'Keel Mango',
    'Koopa Dumpling',
    'Koopa Pilaf',
    'Koopa Tea',
    'Koopasta Dish',
    'Life Shroom',
    'Long-Last Shake',
    'Love Noodle Dish',
    'Love Pudding',
    'Lovely Chocolate',
    'Luxurious Set',
    'Mango Juice',
    'Mango Pudding',
    'Meat Pasta Dish',
    'Megaton Dinner',
    'Meteor Meal',
    'Mighty Tonic',
    'Mild Cocoa Bean',
    'Miracle Dinner',
    'Mistake',
    'Mixed Shake',
    'Mousse',
    'Mushroom Crepe',
    'Odd Dinner',
    'Omelette Plate',
    'Orange Apple',
    'Peach Juice',
    'Peach Tart',
    'Peachy Peach',
    'Pink Apple',
    'Poison Shroom',
    'POW Block',
    'Power Plus',
    'Power Steak',
    'Primordial Dinner',
    'Primordial Fruit',
    'Red Apple',
    'Roast Horsetail',
    'Roast Meat',
    'Roast Shroom Dish',
    'Roast Whacka Bump',
    'Sap Muffin',
    'Sap Soup',
    'Sap Syrup',
    'Shell Shock',
    'Shooting Star',
    'Shroom Broth',
    'Shroom Cake',
    'Shroom Choco-bar',
    'Shroom Delicacy',
    'Shroom Pudding',
    'Shroom Shake',
    'Shroom Steak',
    'Sky Juice',
    'Sleepy Sheep',
    'Slimy Extract',
    'Slimy Shroom',
    'Smelly Herb',
    'Snow Bunny',
    'Snow Cone',
    'Space Food',
    'Spaghetti Plate',
    'Spicy Dinner',
    'Spicy Pasta Dish',
    'Spicy Soup',
    'Stamina Juice',
    'Standard Chocolate',
    'Star Medal',
    'Stop Watch',
    'Super Shroom Shake',
    'Sweet Choco-bar',
    'Sweet Cookie Snack',
    'Thunder Rage',
    'Town Special',
    'Trial Stew',
    'Turtley Leaf',
    'Ultra Shroom Shake',
    'Veggie Set',
    'Volcano Shroom',
    'Volt Shroom',
    'Warm Cocoa',
    'Weird Extract',
    'Whacka Bump',
]